name: Run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Cache Poetry venv
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pre-commit
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock', '.pre-commit-config.yaml') }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies and dev dependencies, and install pre-commit hooks
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install --with dev
      - name: Run run.sh script
        run: |
          chmod +x run.sh
          ./run.sh
        env:
            GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
            GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
            MAKE_API_KEY: ${{ secrets.MAKE_API_KEY }}
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            TARGET_WEEKLY_CHANGE_PERCENTAGE: env.TARGET_WEEKLY_CHANGE_PERCENTAGE
