name: Validate & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Cache Poetry venv
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pre-commit
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock', '.pre-commit-config.yaml') }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies and dev dependencies, and install pre-commit hooks
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install --with dev
          poetry run pre-commit install
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
      - name: Run tests
        run: poetry run pytest
